[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''local card = Card(0,0, 0.5*G.CARD_W, 0.5*G.CARD_H, G.P_CARDS[v[1]], G.P_CENTERS.c_base)'''
position = "at"
payload = '''local card = Card(0,0, 0.5*G.CARD_W, 0.5*G.CARD_H, G.P_CARDS[v[1]], G.P_CENTERS[v[3] or 'c_base'])'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
-- TARGET: main scoring on played cards
'''
position = "after"
payload = '''
if card.ability.name == "Stone Card" then
    G.GAME.ante_stones_scored = (G.GAME.ante_stones_scored or 0) + 1
    G.GAME.hands['rob_stone_flush'].l_chips = G.GAME.hands['rob_stone_flush'].l_chips_base + (G.GAME.hands['rob_stone_flush'].l_chips_scaling * G.GAME.ante_stones_scored)
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
check_and_set_high_score('furthest_ante', G.GAME.round_resets.ante)
'''
position = "after"
payload = '''
G.GAME.ante_stones_scored = 0
G.GAME.hands['rob_stone_flush'].l_chips = G.GAME.hands['rob_stone_flush'].l_chips_base
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
for i=1, hand_space do --draw cards from deck
'''
position = "before"
payload = '''
hand_space = hand_space + G.GAME.green_seal_draws
G.GAME.green_seal_draws = 0
'''
match_indent = true
times = 1


[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
ease_discard(-1)
G.GAME.current_round.discards_used = G.GAME.current_round.discards_used + 1
'''
position = "at"
payload = '''
if G.GAME.orange_seal == false then
    ease_discard(-1)
    G.GAME.current_round.discards_used = G.GAME.current_round.discards_used + 1
end
'''
match_indent = true
times = 1


[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
G.FUNCS.discard_cards_from_highlighted = function(e, hook)
'''
position = "after"
payload = '''
G.GAME.orange_seal = false
'''
match_indent = true
times = 1

